export const GROUPS_DATA = [
  {
    id: "1",
    name: "Weekend Trip Squad",
    totalTransactions: 12,
    approvedTransactions: 10,
    pendingTransactions: 2,
    netAmount: 245.5,
    memberCount: 4,
    lastActivity: "2 hours ago",
  },
  {
    id: "2",
    name: "Roommates Expenses",
    totalTransactions: 28,
    approvedTransactions: 25,
    pendingTransactions: 3,
    netAmount: -89.3,
    memberCount: 3,
    lastActivity: "1 day ago",
  },
  {
    id: "3",
    name: "Birthday Party Group",
    totalTransactions: 8,
    approvedTransactions: 8,
    pendingTransactions: 0,
    netAmount: 156.75,
    memberCount: 6,
    lastActivity: "3 days ago",
  },
  {
    id: "4",
    name: "Office Lunch Bunch",
    totalTransactions: 15,
    approvedTransactions: 12,
    pendingTransactions: 3,
    netAmount: 67.2,
    memberCount: 5,
    lastActivity: "5 hours ago",
  },
];
