# Generated by Django 5.2.3 on 2025-11-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_expense_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='min_floor',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='The minimum debt before AI starts complaining', max_digits=10),
        ),
    ]
