# Generated by Django 5.2.3 on 2025-11-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_group_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('JOIN', 'Member Joined'), ('LEAVE', 'Member Left'), ('RENAME', 'Group Renamed')], max_length=20)),
                ('details', models.TextField(help_text='Details about the action (e.g., user name, old/new group name)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='APP.group')),
            ],
        ),
    ]
