# Generated by Django 5.2.6 on 2025-11-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_grouplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
