# Generated by Django 5.2.6 on 2025-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_expense_status_expensesplit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=10),
        ),
    ]
