# Generated by Django 5.2.8 on 2025-11-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_expense_dispute_reason_alter_expense_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='dispute_reason',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORTATION', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('MISCELLANEOUS', 'Miscellaneous'), ('SUPPLIES', 'Supplies'), ('BILLS', 'Bills')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
