# Generated by Django 5.2.8 on 2025-11-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_remove_expense_dispute_reason_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='APPROVED', max_length=10),
        ),
        migrations.AlterField(
            model_name='expensesplit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='ACCEPTED', max_length=10),
        ),
    ]
